version: 0.0
os: linux
files:  
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall: 
    - location: Scripts/Install_dependencies.sh
      timeout: 300
      run-as: root
  Install: 
    - location: Scripts/After_Install.sh
      timeout: 300
      run-as: root
  ApplicationStart:
    - location: Scripts/Application_Start.sh
      timeout: 300
      run-as: root  
  ApplicationStop: 
    - location: Scripts/Application_Stop.sh
      timeout: 300
      run-as: root
      
